# Generated by Django 4.1.3 on 2022-11-16 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='blog_post',
        ),
    ]
